version: '3'
services:
  name_extractor:
    build:
      context: .
      dockerfile: ./docker/ml.Dockerfile
    image: name_extractor:latest
    volumes:
      - ./:/workdir
    ports:
      - 8888:8888
    container_name: name_extractor_container
    working_dir: /workdir
    command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root

  extractor:
    build:
      context: .
      dockerfile: ./docker/ml.Dockerfile
    image: name_extractor:latest
    volumes:
      - ./:/workdir
    container_name: extractor_container
    working_dir: /workdir
